<b>Declaration<b>

In [1]:
import numpy as np
x=np.array([1,2,3])


<b>Proprietés<b>

In [3]:
x.ndim

1

In [4]:
x.shape

(3,)

In [5]:
x.dtype

dtype('int32')

In [7]:
x=np.array([1,2,3],dtype=np.uint8)

<b>Operations sur vecteur<b>

In [8]:
x=np.array([1,2,3])
y=np.array([1,2,3])
z=x+y
z

array([2, 4, 6])

In [9]:
y=np.ones(shape=(3),dtype=np.int16)

In [10]:
y

array([1, 1, 1], dtype=int16)

In [11]:
x-y

array([0, 1, 2])

In [12]:
x*y

array([1, 2, 3])

In [13]:
x/y


array([1., 2., 3.])

In [14]:
x**y

array([1, 2, 3], dtype=int32)

<b>fonction sur les vecteurs<b>

In [15]:
ages=np.array([28,35,51,26])

In [16]:
ages.min()

26

In [18]:
ages.argmin()

3

In [17]:
ages.argmax()

2

In [20]:
np.mean(ages)

35.0

In [21]:
np.max(ages)

51

In [22]:
ages.sort()

In [23]:
np.sort(ages)

array([26, 28, 35, 51])

In [24]:
np.sort(ages)[::-1]

array([51, 35, 28, 26])

In [25]:
np.var(ages)

96.5

Exemple

In [26]:
ages=([29,30,29,31,30,31])

In [27]:
np.mean(ages)

30.0

In [30]:
ages2=([20,30,40,50,30,10])

In [31]:
np.mean(ages2)

30.0

In [33]:
np.var(ages)

0.6666666666666666

In [32]:
np.var(ages2)

166.66666666666666

<b>Operations sur matrices<b>

In [43]:
x=np.array([[1,2,3],[1,2,3]])
y=np.array([[4,5,6],[4,5,6]])
z=x+y
z

array([[5, 7, 9],
       [5, 7, 9]])

In [44]:
x-y

array([[-3, -3, -3],
       [-3, -3, -3]])

In [45]:
x*y

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [46]:
x**y

array([[  1,  32, 729],
       [  1,  32, 729]])

In [47]:
x/y

array([[0.25, 0.4 , 0.5 ],
       [0.25, 0.4 , 0.5 ]])

<b>Fonctions sur matrices <b>

In [48]:
X=np.array([1,2,3])
Y=np.array([5,6,7])
np.dot(X,Y)

38

In [50]:
x=np.array([[1,2,3],[1,2,3]])
y=np.array([[2],[3],[4]])
np.dot(x,y)

array([[20],
       [20]])

In [51]:
x.min()

1

In [54]:
x.min(axis=0)# retourne le min dans chaque colonne 

array([1, 2, 3])

In [53]:
x.min(axis=1)# retourne le min dans chaque ligne

array([1, 1])

axis=1 => lignes <br>
axis=0 => colonnes

In [55]:
x.sum()

12

In [57]:
x.sum(axis=1)

array([6, 6])

Operations entre vecteur et scalaire

In [58]:
x=np.array([1,2,3])

In [59]:
2*x

array([2, 4, 6])

In [61]:
x/2

array([0.5, 1. , 1.5])

Operation entre matrice et vecteur

In [63]:
X=np.array([[1,2],[2,3],[3,4]])
Y=np.array([2,2])


In [64]:
X+Y

array([[3, 4],
       [4, 5],
       [5, 6]])

In [65]:
X/Y

array([[0.5, 1. ],
       [1. , 1.5],
       [1.5, 2. ]])

In [66]:
X*Y

array([[2, 4],
       [4, 6],
       [6, 8]])

<b> EXERCICE</b>

soit un employé ali ayant comme age 28 et salaire 2100.75

soit l'ensemble d'employés:
<li>
'salma' (age=40,2200.76)</li>
<li>'Rahma' (age=28,3200.76)<li>
'ahmed' (age=45,2100.33)

In [68]:
emps=np.array([[40,2200.76],[28,3200.76],[45,2100.33]])
ali=np.array([28,2100.75])


In [89]:
from math import sqrt
dist=np.empty(shape=)
for emp in emps:
    np.append(dist,sqrt((emp[0]-ali[0])**2+(emp[1]-ali[1])**2))
    #sqrt((emp[0]-ali[0])**2+(emp[1]-ali[1])**2)
    

In [90]:
dist

array([1.38781225e-311, 0.00000000e+000, 1.38778531e-311])