<b>Declaration<b>

In [104]:
import numpy as np
x=np.array([1,2,3])


<b>Proprietés<b>

In [105]:
x.ndim

1

In [106]:
x.shape

(3,)

In [107]:
x.dtype

dtype('int32')

In [108]:
x=np.array([1,2,3],dtype=np.uint8)

<b>Operations sur vecteur<b>

In [109]:
x=np.array([1,2,3])
y=np.array([1,2,3])
z=x+y
z

array([2, 4, 6])

In [110]:
y=np.ones(shape=(3),dtype=np.int16)

In [111]:
y

array([1, 1, 1], dtype=int16)

In [112]:
x-y

array([0, 1, 2])

In [113]:
x*y

array([1, 2, 3])

In [114]:
x/y


array([1., 2., 3.])

In [115]:
x**y

array([1, 2, 3], dtype=int32)

<b>fonction sur les vecteurs<b>

In [116]:
ages=np.array([28,35,51,26])

In [117]:
ages.min()

26

In [118]:
ages.argmin()

3

In [119]:
ages.argmax()

2

In [120]:
np.mean(ages)

35.0

In [121]:
np.max(ages)

51

In [122]:
ages.sort()

In [123]:
np.sort(ages)

array([26, 28, 35, 51])

In [124]:
np.sort(ages)[::-1]

array([51, 35, 28, 26])

In [125]:
np.var(ages)

96.5

Exemple

In [126]:
ages=([29,30,29,31,30,31])

In [127]:
np.mean(ages)

30.0

In [128]:
ages2=([20,30,40,50,30,10])

In [129]:
np.mean(ages2)

30.0

In [130]:
np.var(ages)

0.6666666666666666

In [131]:
np.var(ages2)

166.66666666666666

<b>Operations sur matrices<b>

In [132]:
x=np.array([[1,2,3],[1,2,3]])
y=np.array([[4,5,6],[4,5,6]])
z=x+y
z

array([[5, 7, 9],
       [5, 7, 9]])

In [133]:
x-y

array([[-3, -3, -3],
       [-3, -3, -3]])

In [134]:
x*y

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [135]:
x**y

array([[  1,  32, 729],
       [  1,  32, 729]])

In [136]:
x/y

array([[0.25, 0.4 , 0.5 ],
       [0.25, 0.4 , 0.5 ]])

<b>Fonctions sur matrices <b>

In [137]:
X=np.array([1,2,3])
Y=np.array([5,6,7])
np.dot(X,Y)

38

In [138]:
x=np.array([[1,2,3],[1,2,3]])
y=np.array([[2],[3],[4]])
np.dot(x,y)

array([[20],
       [20]])

In [139]:
x.min()

1

In [140]:
x.min(axis=0)# retourne le min dans chaque colonne 

array([1, 2, 3])

In [141]:
x.min(axis=1)# retourne le min dans chaque ligne

array([1, 1])

axis=1 => lignes <br>
axis=0 => colonnes

In [142]:
x.sum()

12

In [143]:
x.sum(axis=1)

array([6, 6])

Operations entre vecteur et scalaire

In [144]:
x=np.array([1,2,3])

In [145]:
2*x

array([2, 4, 6])

In [146]:
x/2

array([0.5, 1. , 1.5])

Operation entre matrice et vecteur

In [147]:
X=np.array([[1,2],[2,3],[3,4]])
Y=np.array([2,2])


In [148]:
X+Y

array([[3, 4],
       [4, 5],
       [5, 6]])

In [149]:
X/Y

array([[0.5, 1. ],
       [1. , 1.5],
       [1.5, 2. ]])

In [150]:
X*Y

array([[2, 4],
       [4, 6],
       [6, 8]])

<b> EXERCICE</b>

soit un employé ali ayant comme age 28 et salaire 2100.75

soit l'ensemble d'employés:
<li>
'salma' (age=40,2200.76)</li>
<li>'Rahma' (age=28,3200.76)<li>
'ahmed' (age=45,2100.33)

In [151]:
emps=np.array([[40,2200.76],[28,3200.76],[45,2100.33]])
ali=np.array([28,2100.75])


In [155]:
from math import sqrt
dist=np.empty(shape=(emps.shape[0]))
#for i in range(emps.shape()):
 #   dist[i]=sqrt((emps[i]-ali[0])**2+(emps[i]-ali[1])**2)
    #sqrt((emp[0]-ali[0])**2+(emp[1]-ali[1])**2)
for i in range(emps.shape[0]):
    d=ali-emps[i,:]
    d2=d**2
    s=np.sum(d2)
    distance=np.sqrt(s)
    dist[i]=distance
    

In [156]:
dist

array([ 100.72735527, 1100.01      ,   17.00518744])

In [157]:
indice_employe_proche=np.argmin(dist)
indice_employe_proche

2

In [160]:
noms=['Salma','Rahma','Ahmed']
noms[indice_employe_proche]

'Ahmed'

Alternative

In [161]:
noms[np.argmin(np.sqrt(np.sum((emps-ali)**2,axis=1)))]

'Ahmed'